apiVersion: apps/v1
kind: Deployment
metadata:
  name: dork-backend
spec:
  replicas: 1
  revisionHistoryLimit: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app: dork-backend
  template:
    metadata:
      labels:
        app: dork-backend
    spec:
      containers:
      - name: dork-backend-container
        image: europe-west1-docker.pkg.dev/project-444d504d-38fb-4e0d-83e/dork-repo/projectofdork-app:latest
        ports:
        - containerPort: 9867
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: DATABASE_URL
        - name: DB_REQUIRED
          value: "true"
        - name: ADMIN_TOKEN
          valueFrom:
            secretKeyRef:
              name: admin-secret
              key: ADMIN_TOKEN
              optional: true
        
        resources:
          requests:
            cpu: "50m" 
            memory: "128Mi"
          limits:
            cpu: "250m" 
            memory: "256Mi"
        
        
        livenessProbe:
          httpGet:
            path: /health
            port: 9867
          initialDelaySeconds: 5 
          periodSeconds: 10      
        
        
        readinessProbe:
          httpGet:
            path: /ready
            port: 9867
          initialDelaySeconds: 3
          periodSeconds: 5       
