apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: dorkuser
  POSTGRES_PASSWORD: change-me
  POSTGRES_DB: dorkdb
  DATABASE_URL: postgres://dorkuser:change-me@postgres-service:5432/dorkdb?sslmode=disable
